### ISSUE TITLE
压不到一个点上，屏幕疯狂抖动，远距离没法打

### ISSUE THREAD

**Issue by Sakura9s** [wanglingdi/CSGO-mouse#1]
压枪疯狂抖动，压不到一个点上，远距离没法打

**Comment by wanglingdi** [comment]
游戏速度设成1，要是其他的游戏鼠标速度得重新改代码的变量。先去创意工坊测试好。

**Comment by Sakura9s** [comment]
> 游戏速度设成1，要是其他的游戏鼠标速度得重新改代码的变量。先去创意工坊测试好。

我在练枪服测的，鼠标速度等符合要求，是对屏幕分辨率有要求吗？我是4：3，1920X1440

**Comment by Sakura9s** [comment]
> 游戏速度设成1，要是其他的游戏鼠标速度得重新改代码的变量。先去创意工坊测试好。

换ghub后，开火一两次后，就不再自动压枪了，悲

**Comment by Sakura9s** [comment]
放弃了，懒得折腾了

**Comment by 0lili** [comment]
现在cs2了还有用吗，没有的话能更新个cs2的吗
